# Generated by Django 4.1.7 on 2023-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
