# Generated by Django 4.1.7 on 2023-03-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='media',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='time_add',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='time_add',
        ),
    ]
