# Generated by Django 4.1.7 on 2023-03-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_alter_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_resp', to='ad.ad'),
        ),
    ]
